version: "3.8"

services:
  db:
    image: postgres:16
    container_name: vault-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - vault-net

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.4
    container_name: vault-idp
    command:
      - start-dev
      - "--db=postgres"
      - "--db-url=jdbc:postgresql://db:5432/keycloak"
      - "--db-username=${POSTGRES_USER}"
      - "--db-password=${POSTGRES_PASSWORD}"
    environment:
      KC_HOSTNAME: localhost
      KC_HTTP_RELATIVE_PATH: /
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - vault-net

volumes:
  db_data:

networks:
  vault-net:
    driver: bridge
