version: "3.8"

# frontend and backend have been left out for now.

services:
  db:
    image: postgres:16
    container_name: vault-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - vault-net

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.4
    container_name: vault-idp
    command:
      - start-dev
      - "--db=postgres"
      - "--db-url=jdbc:postgresql://db:5432/postgres"
      - "--db-username=postgres"
      - "--db-password=postgres"
    environment:
      KC_HOSTNAME: localhost
      KC_HTTP_RELATIVE_PATH: /
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - vault-net

volumes:
  db_data:

networks:
  vault-net:
    driver: bridge
